# Server configuration
listen_address: ":3000"

# Active modules
active_modules:
  - os
  - cpu
  - gpu
  - de
  - wm
  - theme
  - icons
  - terminal
  - font
  - cursor
  - uptime
  - memory
  - disk
  - network
  - resolution
  - packages
  - swap
  - localip
  - battery
  - poweradapter
  - locale

# Logo configuration
default_logo: "tux"
logo_dir: "./logos"